//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecole_management_data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sections
    {
        public int id { get; set; }
        public string niveau { get; set; }
    }
}
